### ISSUE TITLE
Line not positioned correctly

### ISSUE THREAD

**Issue by sysads** [gunjankothari/jquery.connectingLine#1]
Hi I have tried using this plugin but my lines are not positioned correctly and its not joining as expected - http://snag.gy/3Y2wq.jpg

My HTML:

<!DOCTYPE html>
<html>

<head>

```
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script type="text/javascript" src="js/jquery.svg.min.js"></script>
<script type="text/javascript" src="js/jquery.connectingLine.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>

<link href="css/tmc.css" rel="stylesheet" type="text/css" />
```

</head>

<body>

```
<div class='img_all'>

    <div class="img_logo1"><img src="images/img 1.png" alt="" /></div>

    <div class="img_logo2"><img src="images/img 2.png" alt="" /></div>

    <div class="img_logo3"><img src="images/img 3.png" alt="" /></div>
```

/></div>
    </div>

```
<script type="text/javascript">
var mySVG = $('body').connectSVG();
mySVG.drawLine({
left_node:'.img_logo1',
right_node:'.img_logo2',
horizantal_gap:10
});

        $( ".img_logo1" ).draggable({
      drag: function(event, ui){mySVG.redrawLines();}
    });
    $( ".img_logo1" ).draggable({
      drag: function(event, ui){mySVG.redrawLines();}
    });

</script>
```

</body>
</html>

CSS:

body {
    background: #001a33;
}

.img_all img{
    width: 10%;
    height: auto;
}

.img_logo1 img {
    position: absolute;
    margin-left: 20%;
    margin-top: 0;
    width: 14%;
}

.img_logo2 img {
    margin-left: 74%;
    margin-top: 20%;
    position: absolute;
    width: 14%;
}

.img_logo3 img {
    margin-left: 40%;
    margin-top: 48%;
    position: absolute;
}

**Comment by gunjankothari** [comment]
I think its CSS issue that you have written. Try the following css
body {
    background: #001a33;
}
.img_all img {
    width: 10%;
    height: auto;
}
.img_logo1 img {
    /\* position: absolute; _/
    /_ margin-left: 20%; _/
    /_ margin-top: 0; _/
    width: 14%;
}
.img_logo2 img {
    /_ margin-left: 74%; _/
    /_ margin-top: 20%; _/
    /_ position: absolute; _/
    width: 14%;
}
.img_logo3 img {
    /_ margin-left: 40%; _/
    /_ margin-top: 48%; _/
    /_ position: absolute; */
}
.img_logo1 {
    position: absolute !important;    margin-left: 20%;    margin-top: 0;
}

.img_logo2 {
    margin-left: 74%;    margin-top: 20%;    position: absolute;
}

.img_logo3 {
    margin-left: 40%;    margin-top: 48%;    position: absolute;
}

**Comment by sysads** [comment]
Hi, tried your suggestion but still not luck

**Comment by gunjankothari** [comment]
Can you send me your code in a zip including image?
I will make it working for you.

**Comment by sysads** [comment]
Thanks

Link to dropbox - https://www.dropbox.com/sh/qsqxfojrhimo4lk/AADsuXmamCv7w0YJqoTKLScla?dl=0

**Comment by gunjankothari** [comment]
I will update you in 6 hours Regards,
Gunjan Kothari

```
 On Tuesday, April 28, 2015 4:17 PM, Chelseawillrecover <notifications@github.com> wrote:
```

 ThanksLink to dropbox - https://www.dropbox.com/sh/qsqxfojrhimo4lk/AADsuXmamCv7w0YJqoTKLScla?dl=0—

**Comment by gunjankothari** [comment]
https://www.dropbox.com/sh/0czxat9n14cjc5g/AADNKZWRhULNPCFKWFd73XDMa?dl=0

**Comment by sysads** [comment]
Perfect, that worked. Thanks

**Comment by gunjankothari** [comment]
Wel come.
